### ISSUE TITLE
Missing Libraries

### ISSUE THREAD

**Issue by Andre19926** [timschumi/gmod-chttp#14]
Greetings,

Recently I have the problem that for some reason the latest version of gmod-chttp ceases to function on my server.
So I went ahead and took the version before the latest one (1.3.2) and everything went fine.

Using the 1.4.0-rc1 causes the gmsv_chttp_linux.dll to not work.
I contacted the server host support in a hope that they know what the issue would be. They told me to ask you what dependencies or libraries 1.4.0-rc1 needs to properly function.

Cheers,
Andre19926

**Comment by timschumi** [comment]
I don't think any of the dependencies have changed between v1.3.2 and v1.4.0-rc1. Both versions of the library have been compiled on the same Debian 9 box, and should therefore be compatible with everything that is equally new or newer.

The library shouldn't have any specific dependencies either, all the special libraries that it needs (libz, libssl, libcurl) are contained within the DLL itself, so it only needs compatible versions of the standard libraries (which should already be present on servers which are able to run a Garry's Mod server, although not necessarily at the correct version).

You could also try and use the custom libraries that I made for CentOS 7 (which is quite a bit older than the Debian system that I usually compile on), which are located [here](https://github.com/timschumi/gmod-chttp/files/5144562/chttp-1.4.0-rc1-centos7.zip).

For a few things that would help during debugging:

- Could you get some information about what distribution you are running (arch, version, etc.)? If you have shell access, `cat /etc/lsb-release` and `uname -a` should already give quite a bit of information.
- Does it say anything if you run `lua_run require("chttp")` in the server console?
- If you have a shell, `ldd /path/to/the/dll` should tell us which libraries are found and which aren't.

**Comment by timschumi** [comment]
I have now released [Version 1.4.1](https://github.com/timschumi/gmod-chttp/releases/tag/v1.4.1), which should be compatible with more Linux distributions and provides additional builds with even less dependencies.

Please follow the reworked [Installation instructions](https://github.com/timschumi/gmod-chttp#installation) and test whether the new version (or its `-static` variation) solves your issue. In case the issue is still present, feel free to reopen this issue report.
