### ISSUE TITLE
How do I add parameters to an http request?

### ISSUE THREAD

**Issue by JackRichardson666** [timschumi/gmod-chttp#18]
I can't add the parameter table, I used the same http.Post only put CHTTP and nothing worked

**Comment by timschumi** [comment]
While it uses `HTTP()` internally, `http.Post()` is a different interface and it's not compatible with CHTTP (although, it might be a cool idea to create equivalent wrappers for CHTTP as well).

The documentation for HTTP is located [here](https://wiki.facepunch.com/gmod/Global.HTTP) and the documentation for the request parameters table that it uses is located [here](https://wiki.facepunch.com/gmod/Structures/HTTPRequest).

**Comment by timschumi** [comment]
I now created [an addon](https://steamcommunity.com/sharedfiles/filedetails/?id=2537802091) that provides similiar functions for CHTTP.
