### ISSUE TITLE
Deadlock in TLS/HTTPS connections on CentOS 7

### ISSUE THREAD

**Issue by Alawork** [timschumi/gmod-chttp#19]
Hello there!

When I'm installing Linux 64 version.DLL - bLogs require just Linux version of DLL
When I'm installing Linux version.DLL - it's giving me an error. Attaching screenshot below
When i'm installing Linux-Static.DLL ( obviously with -static delete ), no errors given, but the logs doesn't come to Discord via webhook use.

OC host:
```
centos-release-7-9.2009.1.el7.centos.x86_64
Linux vps32594 2.6.32-042stab145.3 #1 SMP Thu Jun 11 14:05:04 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux
```
![изображение](https://user-images.githubusercontent.com/57138952/122689111-8c687180-d24a-11eb-813d-4240fad4447f.png)

**Comment by timschumi** [comment]
CentOS 7 is so old that you pretty much have to use `-static`.

If bLogs doesn't print an error, the module is very likely to have loaded correctly. Scroll up in the console and check whether you have missed any error output generated by CHTTP.

If you want to manually check whether the library can run successful requests, paste this into the console and run it: `lua_run CHTTP({url = "https://google.com", success = function(c,b,h) print(c) end, failed = print})`. Keep in mind that a player has to be present on the server for requests callbacks to be processed. Alternatively, run `sv_hibernate_think 1` in the console to make requests work even if no player is currently on the server.

**Comment by Alawork** [comment]
I can't really understand what's the problem there
I'll attach some screenshots of code and console:
![изображение](https://user-images.githubusercontent.com/57138952/122692443-4a95f600-d25f-11eb-955e-3240f691acee.png)
![изображение](https://user-images.githubusercontent.com/57138952/122692450-51bd0400-d25f-11eb-8c50-970dacc13a7f.png)

**Comment by timschumi** [comment]
Are you absolutely certain that a player is currently present on your server? Otherwise, requests won't be processed.

Also, please put the newlines at the end of your text outputs instead of the beginning, otherwise there _might_ be issues with line-based buffering.

**Comment by Alawork** [comment]
Yes, I am on the server at this moment 
![изображение](https://user-images.githubusercontent.com/57138952/122737695-83f45300-d2ab-11eb-9a11-3d968e8fe0c3.png)
![изображение](https://user-images.githubusercontent.com/57138952/122737731-8f477e80-d2ab-11eb-9970-5fdc6d80a6fe.png)

**Comment by timschumi** [comment]
Please set `developer 1` to get more verbose output.

Also, after you did that, please provide a full log (as an attachment in text form) until at least the first request happened (feel free to replace any identifying data, but make it obvious if you do so).

**Comment by Alawork** [comment]
developer 1 was entered, no messages
can i send the full log file to you in private messages?
![изображение](https://user-images.githubusercontent.com/57138952/122741924-a6886b00-d2af-11eb-9ed4-6872fb0098d1.png)

**Comment by timschumi** [comment]
Sure. Also, at this point, it might be more efficient if we continue this in a real-time chat instead (for example on [my Discord server](https://discord.gg/S9FdN7G)).

**Comment by timschumi** [comment]
The current TL;DR is that libcurl/OpenSSL will somehow lock up when trying to initiate an HTTPS connection. This only happens with the libcurl/OpenSSL I built, but not when dynamically linking against the systems own libraries. However, it doesn't seem like this is reproducible on a default CentOS 7 installation, so it might be caused by the containerization/host that the hoster is using.

**Comment by timschumi** [comment]
I have just released [new binaries](https://github.com/timschumi/gmod-chttp/releases/tag/v1.5.2) with a significantly updated OpenSSL version. @Alawork, could you check whether the issue still exists for you when using those?

**Comment by Alawork** [comment]
on version 1.7.0. works as it should, sorry for such a late reply
