### ISSUE TITLE
Will support for the null character in the body be added?

### ISSUE THREAD

**Issue by devonium** [timschumi/gmod-chttp#20]

**Comment by timschumi** [comment]
Fixed in commit 411d7b4db3329c6a52521b28cb709bb207d21821 and released in [v1.4.3](https://github.com/timschumi/gmod-chttp/releases/tag/v1.4.3).

**Comment by devonium** [comment]
Sorry but I meant the body that goes into the structure of the HTTP request it was necessary to clarify this
https://github.com/timschumi/gmod-chttp/blob/aba96647712e71cb6e3de49ac51af7440c400c98/src/chttp.cpp#L80

**Comment by timschumi** [comment]
Whoops.

Uh, I can probably do that.

**Comment by timschumi** [comment]
Ok, next try.

Fixed in commit ac1241c4b9cf2958c1209568b0cdf406221cbf1b and released in [v1.4.4](https://github.com/timschumi/gmod-chttp/releases/tag/v1.4.4).

**Comment by devonium** [comment]
Now it gives the error "Unsupported protocol" on [v1.4.2](https://github.com/timschumi/gmod-chttp/releases/tag/v1.4.2) it works fine
