### ISSUE TITLE
Gives the "Unsupported Protocol" error starting from version v1.4.3

### ISSUE THREAD

**Issue by devonium** [timschumi/gmod-chttp#21]
Gives this error only on a URL with the https protocol

**Comment by timschumi** [comment]
It works fine here, and I see no reason why it shouldn't. Can you give a bit more information about your OS so that I can try and replicate it?

**Comment by devonium** [comment]
I think I've figured out what the problem is I probably need to update Windows to the latest version

**Comment by timschumi** [comment]
Having latest Windows shouldn't be required, in fact, it should work on relatively old Windows versions as well.
But I can replicate the issue now, so lets see what I can find...

**Comment by timschumi** [comment]
Fixed in commit 12bfd619e6674d0cc0f4c8e1517ff8d126843ae8 and released in [v1.4.5](https://github.com/timschumi/gmod-chttp/releases/tag/v1.4.5).

Thank you very much for the bug report and sorry for the inconvenience.

**Comment by devonium** [comment]
Thank you very much for spending your time on the library
