### ISSUE TITLE
Random crashes since CHTTP version 1.4.3 (and later)

### ISSUE THREAD

**Issue by FlorianLeChat** [timschumi/gmod-chttp#22]
Since upgrading the module to version 1.4.3 and then 1.4.5, I've been experiencing numerous crashes when using the HTTP functions to communicate with webhooks on my Discord server (especially to signal the launch and shutdown of the server).

When using version 1.4.3, it was impossible for me to communicate with my webhook and caused a game crash when I disconnected from a P2P session or a private server (related to ShutDown hook ?). However in 1.4.5, the situation has improved because my webhook seems to work correctly at server startup but when I shutdown the server or my game in singleplayer, I simply crash.

For information, my game and my local server use Windows and Garry's Mod in 32-bit version (public branch). Here is one of the many crash dumps I can have : [crash.zip](https://github.com/timschumi/gmod-chttp/files/6720309/crash.zip)

If the crashdump is not enough for you I can gladly give you some code to reproduce this issue.

**Comment by timschumi** [comment]
> If the crashdump is not enough for you I can gladly give you some code to reproduce this issue.

I'd greatly appreciate it, since I have no idea how to read mdumps, and it would have to happen on a debug version of the library anyways.

**Comment by timschumi** [comment]
Looking at what I got from the dump so far, it seems like CHTTP isn't even loaded when the server is crashing, and I don't see any log messages that would indicate that CHTTP is used for any request.

If this happens during shutdown, it is possible that this happens after the module has been unloaded, but in that case the crashes already should have happened before that.

**Comment by FlorianLeChat** [comment]
> EDIT: I advise you to change your webhook. I accidentally leaked it while trying to read the mdmp file.

Don't worry, I made the same mistake on Gmod Discord a few hours before posting this message here 😂


> Looking at what I got from the dump so far, it seems like CHTTP isn't even loaded when the server is crashing, and I don't see any log messages that would indicate that CHTTP is used for any request.
> 
> If this happens during shutdown, it is possible that this happens after the module has been unloaded (which invalidates the function reference and the stored hook and would probably cause issues), but in that case the crashes already should have happened before upgrading to v1.4.3.

Sorry for the delay but I've been investigating further and I've discovered something. First of all, it seems that the version is not related to my current issue and that it may have already been present in previous versions. Since some time, I use coroutines to make HTTP requests to improve code readability. By doing some tests, I discovered that using coroutines with CHTTP makes the game crash if you make a request at the `ShutDown` hook, while this is not the case with the default HTTP library.

Another detail, it seems there is no such issue on a dedicated server but only if you use CHTTP in singleplayer or P2P session. So at the moment I don't know if this is a problem with my implementation, an issue with Garry's Mod or a fault on your side. Unfortunately, I can't give you any crashdump because Gmod doesn't generate one when it crashes. Here is the code I used anyway.

```lua
local my_http

if pcall(require, "chttp") and CHTTP ~= nil then
	print("CHTTP loaded")
	my_http = CHTTP
else
	print("Default Gmod HTTP loaded")
	my_http = HTTP
end

function HttpRequest(method, url, data)
	data = data or {}

	local running = coroutine.running()
	local requestData = {
		url = url,
		body = data.body,
		type = data.type,
		method = method,
		headers = data.headers or {},
		parameters = data.parameters or {},

		success = function(code, body, header)
			if code == 204 or (body ~= "" and (code == 200 or code == 201)) then
				coroutine.resume(running, true, body)
			else
				coroutine.resume(running, false, code)
			end
		end,

		failed = function(errorMessage)
			coroutine.resume(running, false, errorMessage)
		end
	}

	my_http(requestData)

	return coroutine.yield()
end

hook.Add("AcceptInput", "test_github", function()
	local message = {
		color = 2031360,
		title = "Server lauched",
		author = {
			name = "Console",
			icon_url = "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
		},
		footer = {
			text = "test footer"
		}
	}

	coroutine.wrap(function()
		local state, response = HttpRequest("POST", "your_discord_webhook_url", {
			type = "application/json",
			body = util.TableToJSON({ embeds = { message } }) -- https://discordjs.guide/popular-topics/embeds.html#using-an-embed-object
		})

		print("Launch request:", state, response)
	end)()

	hook.Remove("AcceptInput", "test_github")
end)

hook.Add("ShutDown", "test_github", function()
	local message = {
		color = 16711680,
		title = "Server shutdown",
		author = {
			name = "Console",
			icon_url = "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
		},
		footer = {
			text = "test footer"
		}
	}

	coroutine.wrap(function()
		local state, response = HttpRequest("POST", "your_discord_webhook_url", {
			type = "application/json",
			body = util.TableToJSON({ embeds = { message } }) -- https://discordjs.guide/popular-topics/embeds.html#using-an-embed-object
		})

		print("Shutdown request:", state, response)
	end)()
end)
```

**Comment by vMajx** [comment]
![image](https://user-images.githubusercontent.com/26248822/123821119-7b042100-d93e-11eb-8f81-b5ab16da9338.png)
Not sure if this helps, but every time my server shuts down or changes level this gets printed in the console. Maybe something freaks out in the middle of sending something and the server is shutting down? idk. hope this helps!

**Comment by FlorianLeChat** [comment]
When was the last time you updated this module?

**Comment by timschumi** [comment]
> Not sure if this helps, but every time my server shuts down or changes level this gets printed in the console. Maybe something freaks out in the middle of sending something and the server is shutting down? idk. hope this helps!

This is apparently a more widespread issue and most likely unrelated to CHTTP. At least I have seen multiple reports of similiar log messages recently.

**Comment by timschumi** [comment]
I think I have found the issue. In the end, it was caused by the fact that the `ShutDown` hook runs after the `Think` hook has already been stopped, which results in no callbacks being run. Using normal callbacks, the game simply doesn't care because nobody will notice. But if that callback is supposed to resume a coroutine, the game will keep around that coroutine (that has never been resumed), will notice that it's still there when the Lua state shuts down and gets terribly unhappy about that.

Since I got similiar assert failures when trying to replicate this in a dedicated server, I assume that this is also what @vMajx has been running into.

I have uploaded a bunch of test builds [here](https://github.com/timschumi/gmod-chttp/files/6759794/chttp_coro_fix.zip). Can both of you check if that fixes your issues?

**Comment by FlorianLeChat** [comment]
I just tested with the same conditions as last time and it seems that everything works fine. I also tested this on a Linux dedicated server and no problems either. Thanks for taking the time to fix this! 👍

**Comment by vMajx** [comment]
> I think I have found the issue. In the end, it was caused by the fact that the `ShutDown` hook runs after the `Think` hook has already been stopped, which results in no callbacks being run. Using normal callbacks, the game simply doesn't care because nobody will notice. But if that callback is supposed to resume a coroutine, the game will keep around that coroutine (that has never been resumed), will notice that it's still there when the Lua state shuts down and gets terribly unhappy about that.
> 
> Since I got similiar assert failures when trying to replicate this in a dedicated server, I assume that this is also what @vMajx has been running into.
> 
> I have uploaded a bunch of test builds [here](https://github.com/timschumi/gmod-chttp/files/6759794/chttp_coro_fix.zip). Can both of you check if that fixes your issues?

@timschumi Nice work fixing the issue, however this problem still persists if nobody connects to the server first. Think is never called until someone connects to the server. The server still crashes when you try to changelevel or restart it. In the meantime setting `sv_hibernate_think` to `1` solves this issue.

**Comment by vMajx** [comment]
> I think I have found the issue. In the end, it was caused by the fact that the `ShutDown` hook runs after the `Think` hook has already been stopped, which results in no callbacks being run. Using normal callbacks, the game simply doesn't care because nobody will notice. But if that callback is supposed to resume a coroutine, the game will keep around that coroutine (that has never been resumed), will notice that it's still there when the Lua state shuts down and gets terribly unhappy about that.
> 
> Since I got similiar assert failures when trying to replicate this in a dedicated server, I assume that this is also what @vMajx has been running into.
> 
> I have uploaded a bunch of test builds [here](https://github.com/timschumi/gmod-chttp/files/6759794/chttp_coro_fix.zip). Can both of you check if that fixes your issues?

Testing it so far, it works great! thanks for fixing it.
