### ISSUE TITLE
Sending _GET and _POST in one request does not work

### ISSUE THREAD

**Issue by Leystryku** [timschumi/gmod-chttp#23]
Hello,
in one of my addons I automatically use CHTTP if it is installed and otherwise I use the normal gmod HTTP implementation. Turns out, people have been complaining about a post request not working when CHTTP is installed. Uninstalling it fixes it. The only odd thing I notice about the request  is, it uses both - _GET and _POST

ex:
```
function http.CPost( url, params, onsuccess, onfailure, header )
	local request = {
		url			= url,
		method		= "post",
		parameters	= params,
		headers		= header or {},

		success = function( code, body, headers )

			if ( !onsuccess ) then return end

			onsuccess( body, body:len(), headers, code )

		end,

		failed = function( err )

			if ( !onfailure ) then return end

			onfailure( err )

		end
	}

	OurHTTP( request )
end

    local data = {}

    for k, v in pairs(player.GetHumans()) do
        table.insert(data, {v:Name(), v:SteamID64(), v:TimeConnected()})
    end


    local curip = game.GetIPAddress()
    local iptbl = string.Explode(":", curip)

    local post = {
        key = serverkey,
        address = curip,
        ip = iptbl[1],
        port = iptbl[2],
        hostname = GetHostName(),
        gamemode = engine.ActiveGamemode(),
        map = game.GetMap(),
        players = util.TableToJSON(data),
        max_players = tostring(game.MaxPlayers())
    }

    local url = website .. "/index.php?/api/servers/update"

    http.CPost(url, post, function( result )
            print('\n---LeyScreenCap.SendServerInfo---')
            print('url: '..url)
            print(result)
            print('---END---\n')
    end, function( err )
            print('\n---LeyScreenCap.SendServerInfo (error)---')
            print('url: '..url)
            print(err)
            print('---END---\n')
    end)
```

**Comment by timschumi** [comment]
It doesn't seem like I can reproduce the issue. Are you sure that the code snippet that you sent successfully fails?

There is nothing in here that would cause the server to receive both a GET and a POST request (if I understood correctly?). Could you show your OurHTTP function? What OS and what branch does this happen on?

**Comment by Leystryku** [comment]
I will try to gather more intel and then I will get back to you

**Comment by timschumi** [comment]
Ah, I think I see what the issue is. When dumping the request through PHP, the requests sent by `HTTP()` have their `$_POST` array populated correctly. Requests sent by `CHTTP()` apparently don't.

**Comment by timschumi** [comment]
I have fixed the issue with encoding the data, can you check if that fully fixes your issue?

The test builds are attached [here](https://github.com/timschumi/gmod-chttp/files/6759711/chttp_form_fix.zip).

**Comment by Leystryku** [comment]
@timschumi I will get a customer to test and then get back to you

**Comment by Leystryku** [comment]
Confirmed, works perfectly fine now :P
![image](https://user-images.githubusercontent.com/6385154/124397209-ed924980-dd0e-11eb-86e1-3877eb1b3d4a.png)
