### ISSUE TITLE
Callback timer stops running if a callback throws an error

### ISSUE THREAD

**Issue by timschumi** [timschumi/gmod-chttp#26]
Make sure that the timer is either readded in such a case, or that errors don't get propagated outside of the callback at all.

**Comment by ventz-lgtm** [comment]
Just got this too, very frustrating. One error and no http messages will be processed any more

**Comment by timschumi** [comment]
I put up a preliminary fix, but I still need to investigate whether that is sufficient before making a release.

The binaries are available [here](https://github.com/timschumi/gmod-chttp/files/12301342/gmod-chttp-1.8.2-2-g533df17-binaries.zip).

**Comment by timschumi** [comment]
Fixed in 533df17b603b735a2aa40acd91b514ef8708588c and released in [version 1.9.0](https://github.com/timschumi/gmod-chttp/releases/tag/v1.9.0).
